import type { Timestamp } from 'firebase/firestore';

export type Lang = 'ar' | 'en';

/** The two markets. Every inquiry carries one so the pipeline can be filtered per country. */
export type CountryCode = 'SA' | 'AE';

// ---------------- Users / Roles ----------------
export interface PermissionOverrides {
  granted: string[];
  denied: string[];
}

export type UserStatus = 'active' | 'inactive' | 'deleted';

export interface AppUser {
  uid: string;
  email: string;
  nameAr: string;
  nameEn: string;
  phone?: string;
  photoUrl?: string;
  roleId: string;
  department?: string;
  branch?: string;
  language: Lang;
  themeId: string;
  darkMode: 'light' | 'dark' | 'system';
  status: UserStatus;
  isSuperAdmin?: boolean;
  mustChangePassword?: boolean;
  permissionOverrides: PermissionOverrides;
  effectivePermissions: string[];
  createdAt?: Timestamp;
  createdBy?: string;
  updatedAt?: Timestamp;
  lastLoginAt?: Timestamp;
}

export interface Role {
  id: string;
  nameAr: string;
  nameEn: string;
  descriptionAr?: string;
  descriptionEn?: string;
  permissions: string[];
  isSystem?: boolean;
  createdAt?: Timestamp;
}

// ---------------- Activity log ----------------
export type ActivityAction =
  | 'CREATE' | 'UPDATE' | 'DELETE' | 'VIEW' | 'LOGIN' | 'LOGOUT' | 'LOGIN_FAILED'
  | 'APPROVE' | 'REJECT' | 'EXPORT' | 'PERMISSION_CHANGE' | 'STATUS_CHANGE' | 'ASSIGN';

/** what a log entry needs in order to be reversible from the activity log */
export type UndoPayload =
  | { kind: 'restore'; trashId: string }
  | { kind: 'fields'; path: string; values: Record<string, unknown> };

/** a deleted bundle held for 30 days so it can be put back */
export interface TrashItem {
  id: string;
  module: string;
  label: string;
  recordId?: string;
  docCount: number;
  docs: { path: string; data: Record<string, unknown> }[];
  deletedAt: Timestamp;
  deletedBy: string;
  deletedByName: string;
  expiresAt: Timestamp;
}

export interface ActivityLog {
  id: string;
  timestamp: Timestamp;
  userId: string;
  userName: string;
  userEmail: string;
  roleId: string;
  action: ActivityAction;
  module: string;
  recordId?: string;
  recordLabel?: string;
  field?: string;
  oldValue?: string;
  newValue?: string;
  descriptionAr: string;
  descriptionEn: string;
  userAgent?: string;
  sessionId?: string;
  /** present when the action can be reversed with one click */
  undo?: UndoPayload;
  undoneAt?: Timestamp;
  undoneBy?: string;
  undoneByName?: string;
}

// ---------------- Master data ----------------
export interface Client {
  id: string;
  nameAr: string;
  nameEn: string;
  contactPerson?: string;
  phone?: string;
  email?: string;
  country?: CountryCode;
  city?: string;
  tier?: 'A' | 'B' | 'C';
  isActive: boolean;
  createdAt?: Timestamp;
  createdBy?: string;
}

export interface Project {
  id: string;
  nameAr: string;
  nameEn: string;
  clientId: string;
  country?: CountryCode;
  city?: string;
  isActive: boolean;
  createdAt?: Timestamp;
  createdBy?: string;
}

/**
 * An engineer or salesperson who belongs to the company but has NO login account.
 * Used purely to attribute inquiries and projects to the right person.
 */
export type TeamMemberType = 'engineer' | 'salesperson' | 'both';

export interface TeamMember {
  id: string;
  name: string;
  type: TeamMemberType;
  country?: CountryCode;
  phone?: string;
  email?: string;
  isActive: boolean;
  createdAt?: Timestamp;
  createdBy?: string;
}

// ---------------- Workflow ----------------
export type InquiryStatus =
  | 'NEW'
  | 'FILE_REVIEW'
  | 'WAITING_INFO'
  | 'PRIORITY_ASSIGNMENT'
  | 'ASSIGNED'
  | 'PROCESSING'
  | 'COSTING'
  | 'QUOTATION_PREP'
  | 'UNDER_REVIEW'
  | 'REVISION_REQUIRED'
  | 'APPROVED'
  | 'SENT_TO_SALES'
  | 'SENT_TO_CLIENT'
  | 'FOLLOW_UP'
  | 'CLIENT_REVISION'
  | 'WON'
  | 'LOST'
  | 'NO_BID'
  | 'CANCELLED'
  | 'ON_HOLD';

export type Priority = 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW';

export interface Inquiry {
  id: string;
  inquiryNo: string;
  /** whether the number was typed by a user or generated by the counter */
  inquiryNoSource?: 'auto' | 'manual';
  clientId: string;
  clientName: string;
  projectId?: string;
  projectName?: string;
  country?: CountryCode;
  salespersonId: string;
  salespersonName: string;
  assignedEngineerId?: string;
  assignedEngineerName?: string;
  /** all engineers working this inquiry (primary first); assignedEngineerId stays the responsible one */
  engineerIds?: string[];
  engineerNames?: string[];
  scopeAr: string;
  scopeEn: string;
  scopeType?: string;
  receivedAt: Timestamp;
  requiredSubmissionDate?: Timestamp;
  priority?: Priority;
  prioritySource?: 'auto' | 'manual';
  priorityReason?: string;
  status: InquiryStatus;
  previousStatus?: InquiryStatus;
  deadlineAt?: Timestamp;
  /** the moment the assigned engineer confirmed he received the inquiry — the work clock starts here */
  acknowledgedAt?: Timestamp;
  acknowledgedBy?: string;
  acknowledgedByName?: string;
  /** working minutes between receipt and acknowledgement (first response) */
  firstResponseMin?: number;
  processingStartedAt?: Timestamp;
  processingCompletedAt?: Timestamp;
  pausedAt?: Timestamp;
  pausedMinutes: number;
  missingInfo?: string[];
  missingInfoRequestedAt?: Timestamp;
  missingInfoReceivedAt?: Timestamp;
  estimatedValue?: number;
  finalQuotationValue?: number;
  /** how many problems were logged against this inquiry */
  issueCount?: number;
  openIssueCount?: number;
  currentQuotationId?: string;
  currentQuotationNo?: string;
  currentQuotationStatus?: QuotationStatus;
  currentQuotationRevision?: number;
  outcome?: 'WON' | 'LOST' | 'NO_BID' | 'CANCELLED';
  lostReason?: string;
  lostNote?: string;
  competitorPrice?: number;
  awardValue?: number;
  poNumber?: string;
  closedAt?: Timestamp;
  nextFollowUpAt?: Timestamp;
  createdBy: string;
  createdAt: Timestamp;
  updatedBy?: string;
  updatedAt?: Timestamp;
  isDeleted?: boolean;
}

export interface StatusHistory {
  id: string;
  from?: InquiryStatus;
  to: InquiryStatus;
  by: string;
  byName: string;
  at: Timestamp;
  note?: string;
}

export interface Remark {
  id: string;
  text: string;
  by: string;
  byName: string;
  at: Timestamp;
}

export interface Attachment {
  id: string;
  name: string;
  url: string;
  path: string;
  size: number;
  contentType: string;
  by: string;
  byName: string;
  at: Timestamp;
}

export interface FollowUp {
  id: string;
  seq: number;
  channel: 'call' | 'email' | 'whatsapp' | 'visit' | 'other';
  note: string;
  result?: string;
  nextAt?: Timestamp;
  by: string;
  byName: string;
  at: Timestamp;
}

// ---------------- Quotation ----------------
/**
 * PIQCS does not price anything — the pricing happens in the main system.
 * A quotation here is just its reference number, its value and where it stands.
 */
export type QuotationStatus =
  | 'DRAFT' | 'UNDER_REVIEW' | 'REVISION_REQUIRED' | 'APPROVED' | 'REJECTED'
  | 'SENT_TO_SALES' | 'SENT_TO_CLIENT' | 'SUPERSEDED';

export interface Quotation {
  id: string;
  quotationNo: string;
  inquiryId: string;
  inquiryNo: string;
  clientName: string;
  country?: CountryCode;
  revision: number;
  /** total value as produced by the main pricing system */
  total: number;
  currency?: string;
  notes?: string;
  status: QuotationStatus;
  /** who this was sent to for approval */
  approverIds?: string[];
  approverNames?: string[];
  revisionReason?: string;
  reviewRemark?: string;
  reviewedBy?: string;
  reviewedByName?: string;
  reviewedAt?: Timestamp;
  submittedAt?: Timestamp;
  sentToSalesAt?: Timestamp;
  sentToSalesBy?: string;
  sentToClientAt?: Timestamp;
  sentToClientBy?: string;
  sentToClientChannel?: string;
  createdBy: string;
  createdByName: string;
  createdAt: Timestamp;
  updatedAt?: Timestamp;
}

// ---------------- Issues (problem log) ----------------
export type IssueType =
  | 'missing_info' | 'client_delay' | 'unclear_drawings' | 'site_visit_needed'
  | 'internal_delay' | 'engineer_overload' | 'approval_delay' | 'pricing_delay'
  | 'wrong_data' | 'scope_change' | 'other';

export type IssueSeverity = 'LOW' | 'MEDIUM' | 'HIGH';

/** A problem that held an inquiry up — logged so the office can tally causes and owners. */
export interface Issue {
  id: string;
  inquiryId: string;
  inquiryNo: string;
  country?: CountryCode;
  type: IssueType;
  severity: IssueSeverity;
  description: string;
  /** who the problem sits with (a user or a roster member) */
  responsibleId?: string;
  responsibleName?: string;
  status: 'OPEN' | 'RESOLVED';
  /** working minutes the inquiry lost to this problem */
  lostMin?: number;
  resolution?: string;
  resolvedAt?: Timestamp;
  resolvedBy?: string;
  resolvedByName?: string;
  createdBy: string;
  createdByName: string;
  createdAt: Timestamp;
  updatedAt?: Timestamp;
}

// ---------------- Extensions ----------------
export interface ExtensionRequest {
  id: string;
  inquiryId: string;
  inquiryNo: string;
  currentDeadline: Timestamp;
  requestedDeadline: Timestamp;
  reason: string;
  status: 'PENDING' | 'APPROVED' | 'REJECTED';
  requestedBy: string;
  requestedByName: string;
  requestedAt: Timestamp;
  decidedBy?: string;
  decidedByName?: string;
  decidedAt?: Timestamp;
  decisionNote?: string;
  approvedDeadline?: Timestamp;
}

// ---------------- Tasks ----------------
export type TaskStatus = 'OPEN' | 'IN_PROGRESS' | 'DONE' | 'CANCELLED';

/** A unit of work a manager hands to one person. The assignee sees it in "My tasks" and gets a notification. */
export interface WorkTask {
  id: string;
  title: string;
  description?: string;
  inquiryId?: string;
  inquiryNo?: string;
  country?: CountryCode;
  assignedTo: string;
  assignedToName: string;
  assignedBy: string;
  assignedByName: string;
  /** links the copies of one task assigned to several engineers at once */
  groupId?: string;
  priority: Priority;
  dueAt?: Timestamp;
  status: TaskStatus;
  startedAt?: Timestamp;
  completedAt?: Timestamp;
  resultNote?: string;
  /** working minutes between assignment and the assignee starting */
  pickupMin?: number;
  createdAt: Timestamp;
  updatedAt?: Timestamp;
}

// ---------------- Notifications ----------------
export type NotificationType = 'system' | 'broadcast' | 'alert';
export type NotificationCategory = 'today' | 'week' | 'urgent';

export interface AppNotification {
  id: string;
  userId: string;
  titleAr: string;
  titleEn: string;
  bodyAr?: string;
  bodyEn?: string;
  link?: string;
  read: boolean;
  level: 'info' | 'warning' | 'danger' | 'success';
  type: NotificationType; // 'system' = deadline alert, 'broadcast' = رسالة من المدير, 'alert' = نبيهات أخرى
  category?: NotificationCategory; // للتصنيف: اليوم، الاسبوع، مهمة جداً
  createdAt: Timestamp;
  expiresAt?: Timestamp; // متى تختفي الرسالة
  sentBy?: string; // من أرسلها (لمدير النظام)
  sentByName?: string;
  recipients?: string[]; // قائمة المستخدمين المُستهدفين
  readBy?: Record<string, Timestamp>; // {userId: readAt}
  deletedBy?: Record<string, Timestamp>; // {userId: deletedAt} - لتتبع من حذفها
}

// ---------------- Settings ----------------
export interface GeneralSettings {
  companyNameAr: string;
  companyNameEn: string;
  logoUrl?: string;
  defaultLanguage: Lang;
  defaultThemeId: string;
  allowUserTheme: boolean;
  currency: string;
  slaHours: Record<Priority, number>;
  workingHours: { start: string; end: string; workDays: number[] };
  holidays: string[];
  priorityAutoConfirmHours: number;
  logRetentionMonths: number;
  quotationValidityDays: number;
  inquiryPrefix: string;
  quotationPrefix: string;
  /** 'auto' = the system generates INQ-2026-00001; 'manual' = the user types the number himself */
  inquiryNumbering: 'auto' | 'manual';
  quotationNumbering: 'auto' | 'manual';
  /** country pre-selected on a new inquiry */
  defaultCountry: CountryCode;
  /** neon effect on the copyright signature — admin-controlled */
  copyrightFx?: CopyrightFx;
}

export type CopyrightFxStyle = 'sweep' | 'glow' | 'pulse' | 'frame' | 'box' | 'flicker';
export interface CopyrightFx {
  enabled: boolean;
  style: CopyrightFxStyle;
  /** empty/undefined = follow the active theme's accent color */
  color?: string;
}

export interface ThemeDef {
  id: string;
  nameAr: string;
  nameEn: string;
  colors: {
    primary: string; secondary: string; accent: string;
    bg: string; surface: string; border: string; text: string; muted: string;
    success: string; warning: string; danger: string; info: string;
  };
  dark: {
    bg: string; surface: string; border: string; text: string; muted: string;
  };
  isSystem?: boolean;
}
